insert into students (first_name, last_name, email, requested_courses) values ('Danny', 'Bourchier', 'dbourchier0@aboutads.info', 'Tenge');
insert into students (first_name, last_name, email, requested_courses) values ('Lanni', 'Kiellor', 'lkiellor1@globo.com', 'Peso');
insert into students (first_name, last_name, email, requested_courses) values ('Lolita', 'Sapwell', 'lsapwell2@yellowpages.com', 'Zloty');
insert into students (first_name, last_name, email, requested_courses) values ('Brendin', 'Austin', 'baustin3@shareasale.com', 'Shilling');
insert into students (first_name, last_name, email, requested_courses) values ('Jacky', 'Coneybeer', 'jconeybeer4@joomla.org', 'Yuan Renminbi');
insert into students (first_name, last_name, email, requested_courses) values ('Melania', 'Burbage', 'mburbage5@apple.com', 'Rupiah');
insert into students (first_name, last_name, email, requested_courses) values ('Jule', 'Ocklin', 'jocklin6@comsenz.com', 'Ruble');
insert into students (first_name, last_name, email, requested_courses) values ('Ev', 'Beeckx', 'ebeeckx7@shareasale.com', 'Yuan Renminbi');
insert into students (first_name, last_name, email, requested_courses) values ('Chad', 'Tudball', 'ctudball8@msn.com', 'Peso');
insert into students (first_name, last_name, email, requested_courses) values ('Ellene', 'LLelweln', 'ellelweln9@un.org', 'Kuna');
insert into students (first_name, last_name, email, requested_courses) values ('Charisse', 'Collinette', 'ccollinettea@rakuten.co.jp', 'Rupiah');
insert into students (first_name, last_name, email, requested_courses) values ('Felipa', 'Girauld', 'fgirauldb@bluehost.com', 'Pa''anga');
insert into students (first_name, last_name, email, requested_courses) values ('Carley', 'Durnill', 'cdurnillc@simplemachines.org', 'Lempira');
insert into students (first_name, last_name, email, requested_courses) values ('Griffy', 'Sivier', 'gsivierd@posterous.com', 'Hryvnia');
insert into students (first_name, last_name, email, requested_courses) values ('Teodora', 'Spadollini', 'tspadollinie@deviantart.com', 'Baht');
insert into students (first_name, last_name, email, requested_courses) values ('Catharine', 'Whiffen', 'cwhiffenf@globo.com', 'Zloty');
insert into students (first_name, last_name, email, requested_courses) values ('Laurence', 'Coulman', 'lcoulmang@so-net.ne.jp', 'Euro');
insert into students (first_name, last_name, email, requested_courses) values ('Loy', 'Buttler', 'lbuttlerh@buzzfeed.com', 'Naira');
insert into students (first_name, last_name, email, requested_courses) values ('Pansie', 'Rehorek', 'prehoreki@fastcompany.com', 'Peso');
insert into students (first_name, last_name, email, requested_courses) values ('Monty', 'Feveryear', 'mfeveryearj@bbb.org', 'Tenge');
insert into students (first_name, last_name, email, requested_courses) values ('Saul', 'Spall', 'sspallk@intel.com', 'Rupiah');
insert into students (first_name, last_name, email, requested_courses) values ('Sydelle', 'Danser', 'sdanserl@sakura.ne.jp', 'Rupiah');
insert into students (first_name, last_name, email, requested_courses) values ('Myrtle', 'Chagg', 'mchaggm@netscape.com', 'Peso');
insert into students (first_name, last_name, email, requested_courses) values ('Brynne', 'Catton', 'bcattonn@elegantthemes.com', 'Zloty');
insert into students (first_name, last_name, email, requested_courses) values ('Hali', 'Balogh', 'hbalogho@arstechnica.com', 'Franc');
insert into students (first_name, last_name, email, requested_courses) values ('Gillan', 'Drakers', 'gdrakersp@fda.gov', 'Peso');
insert into students (first_name, last_name, email, requested_courses) values ('Devan', 'Todarini', 'dtodariniq@rakuten.co.jp', 'Rupiah');
insert into students (first_name, last_name, email, requested_courses) values ('Marshal', 'Connors', 'mconnorsr@cocolog-nifty.com', 'Rupee');
insert into students (first_name, last_name, email, requested_courses) values ('Kaleena', 'Quinton', 'kquintons@pen.io', 'Peso');
insert into students (first_name, last_name, email, requested_courses) values ('Teirtza', 'Harder', 'thardert@taobao.com', 'Bolivar');
insert into students (first_name, last_name, email, requested_courses) values ('Tabbi', 'Worman', 'twormanu@g.co', 'Ruble');
insert into students (first_name, last_name, email, requested_courses) values ('Felicio', 'Kerrod', 'fkerrodv@bravesites.com', 'Yuan Renminbi');
insert into students (first_name, last_name, email, requested_courses) values ('Birgitta', 'Addyman', 'baddymanw@mapy.cz', 'Lari');
insert into students (first_name, last_name, email, requested_courses) values ('Megan', 'Kilbourn', 'mkilbournx@istockphoto.com', 'Birr');
insert into students (first_name, last_name, email, requested_courses) values ('Isador', 'Challener', 'ichallenery@ask.com', 'Rupiah');
insert into students (first_name, last_name, email, requested_courses) values ('Chrissie', 'Sperwell', 'csperwellz@omniture.com', 'Dollar');
insert into students (first_name, last_name, email, requested_courses) values ('Casi', 'Luciani', 'cluciani10@github.com', 'Baht');
insert into students (first_name, last_name, email, requested_courses) values ('Fifine', 'Rait', 'frait11@usnews.com', 'Rupiah');
insert into students (first_name, last_name, email, requested_courses) values ('Wilburt', 'Champley', 'wchampley12@dell.com', 'Koruna');
insert into students (first_name, last_name, email, requested_courses) values ('Raynard', 'Hardi', 'rhardi13@google.com.hk', 'Shekel');
insert into students (first_name, last_name, email, requested_courses) values ('Amalea', 'Enderwick', 'aenderwick14@phpbb.com', 'Rupiah');
insert into students (first_name, last_name, email, requested_courses) values ('Orran', 'Hallett', 'ohallett15@artisteer.com', 'Euro');
insert into students (first_name, last_name, email, requested_courses) values ('Richy', 'Rendbaek', 'rrendbaek16@ameblo.jp', 'Euro');
insert into students (first_name, last_name, email, requested_courses) values ('Chlo', 'Bromehead', 'cbromehead17@reddit.com', 'Ruble');
insert into students (first_name, last_name, email, requested_courses) values ('Eimile', 'Crutchley', 'ecrutchley18@ca.gov', 'Yuan Renminbi');
insert into students (first_name, last_name, email, requested_courses) values ('Claus', 'Armes', 'carmes19@youtu.be', 'Yuan Renminbi');
insert into students (first_name, last_name, email, requested_courses) values ('Veronica', 'Fishwick', 'vfishwick1a@so-net.ne.jp', 'Peso');
insert into students (first_name, last_name, email, requested_courses) values ('Gabrila', 'Coultar', 'gcoultar1b@arstechnica.com', 'Koruna');
insert into students (first_name, last_name, email, requested_courses) values ('Jessi', 'Cotton', 'jcotton1c@kickstarter.com', 'Real');
insert into students (first_name, last_name, email, requested_courses) values ('Ortensia', 'Tredwell', 'otredwell1d@paginegialle.it', 'Real');
